title        = "Nutresi"
baseURL      = "https://nutresi.com/"
languageCode = "en-us"
theme        = "nutresi"
themesDir    = "themes"
assetDir     = "themes/nutresi/static"
publishDir   = "docs"

defaultContentLanguage     = "id"
enableRobotsTXT            = true
disableRSS                 = true
disableHugoGeneratorInject = true
disableKinds               = ["taxonomy", "taxonomyTerm", "RSS"]

googleAnalytics = "UA-145441322-5"

[outputs]
  home = ["HTML", "JSON"]

[permalinks]
  posts = "/:title"